import{S as u,i as d}from"./assets/vendor-0fc460d7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const f="44405907-01ac5a46b548f68b2a274235a",m="https://pixabay.com/api/";async function h(t){const r=`${m}?key=${f}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true`;try{return(await(await fetch(r)).json()).hits}catch(o){throw console.error("Error fetching the images:",o),o}}function p(t){t.innerHTML=""}function y(t,r){const o=t.map(e=>`
        <a href="${e.largeImageURL}" class="gallery__item">
            <img src="${e.webformatURL}" alt="${e.tags}" class="gallery__image" />
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${e.likes}</p>
                <p class="info-item"><b>Views:</b> ${e.views}</p>
                <p class="info-item"><b>Comments:</b> ${e.comments}</p>
                <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
            </div>
        </a>
    `).join("");r.insertAdjacentHTML("beforeend",o),new u(".gallery a").refresh()}function a(t,r){d[t]({title:t.charAt(0).toUpperCase()+t.slice(1),message:r})}const g=document.getElementById("searchForm"),b=document.getElementById("searchQuery"),c=document.getElementById("results");g.addEventListener("submit",async t=>{t.preventDefault();const r=b.value.trim();if(!r){a("error","Search query cannot be empty");return}p(c),L();try{const o=await h(r);l(),o.length>0?y(o,c):a("info","Sorry, there are no images matching your search query. Please try again!")}catch{l(),a("error","Something went wrong. Please try again later.")}});function L(){c.innerHTML='<div class="loader"></div>'}function l(){const t=document.querySelector(".loader");t&&t.remove()}
//# sourceMappingURL=commonHelpers.js.map
